import Vue from 'vue'
import { Sku, Loading, Empty, PullRefresh, ActionSheet, Badge, Icon, Button, Rate, Tabbar, TabbarItem, NavBar, Toast, Search, Swipe, SwipeItem, Grid, GridItem } from 'vant'
Vue.use(Search)
Vue.use(Toast)
Vue.use(NavBar)
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(Rate)
Vue.use(Button)
Vue.use(Swipe)
Vue.use(SwipeItem)
Vue.use(Grid)
Vue.use(GridItem)
Vue.use(Icon)
Vue.use(Badge)
Vue.use(ActionSheet)
Vue.use(PullRefresh)
Vue.use(Empty)
Vue.use(Loading)
Vue.use(Sku)
